from tkinter import * 
root=Tk()
root.geometry("644x444")
root.title("VS CODE")
p1 = PhotoImage(file = 'vs.png')
root.iconphoto(False, p1)
f1=Frame(root,bg="grey",borderwidth=2)
f1.pack(side=LEFT,fill=Y)
l1=Label(f1,text="             ",bg="gray")
l1.pack()
f2=Frame(root,bg="Black",borderwidth=105)
f2.pack(side=LEFT,fill=Y)
l2=Label(f2,text="TKINTER",bg="black",fg="white")
l2.pack()
f3=Frame(root,bg="gray",borderwidth=7)
f3.pack(fill=X)
l3=Label(f3,text='3.py',bg="gray",fg="white")
l3.pack()
f4=Frame(root,bg="white",borderwidth=170,)
f4.pack(fill=X)
l4=Label(f4,text='3.py',bg="white",fg="black")
l4.pack()
root.mainloop()